package view

import (
	"fmt"
	"strings"
)

// Man renders phi's man page from the same Commands list Help and
// ZshCompletion use (S-15 AGENT: "generated, not hand-written" — one
// source, three renderings, so a new verb is documented once, not
// authored separately as troff prose). It is never checked into any
// repository: phi-packages' PKGBUILD runs `phi man` at package time and
// installs the output directly (S-15 DONE WHEN: "regenerated by the
// build, not committed by hand").
func Man(version string) string {
	// .TH title section date source manual: date is left empty rather than
	// embedding a build timestamp, since this output has to be
	// byte-reproducible from the same version string alone, not merely
	// regenerated — mandoc -Tlint flags the empty date ("missing date,
	// using \"\"") but still renders correctly; that one warning is the
	// accepted cost of reproducibility, not an oversight. Version goes in
	// the source slot, which is what renders in the page's footer.
	var b strings.Builder
	fmt.Fprintf(&b, ".TH PHI 1 \"\" \"phi %s\" \"phi manual\"\n", version)
	b.WriteString(".SH NAME\n")
	b.WriteString("phi \\- the unified phiOS command-line interface\n")
	b.WriteString(".SH SYNOPSIS\n")
	b.WriteString(".B phi\n.I command\n.RI [ arguments ... ]\n")
	b.WriteString(".SH DESCRIPTION\n")
	b.WriteString("phi is phiOS's single command-line entry point (ADR 016/017).\n")
	b.WriteString("A command not listed below is looked up as\n.B phi-<command>\non\n.BR PATH .\n")

	b.WriteString(".SH COMMANDS\n")
	for _, c := range Commands {
		fmt.Fprintf(&b, ".TP\n.B %s\n%s\n", c.Name, c.Summary)
	}
	b.WriteString(".TP\n.B \\-\\-version\nprint the version\n")

	return b.String()
}
